# Generated by Django 5.1.3 on 2024-11-26 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(default='', max_length=128)),
                ('content', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation.lang')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id', 'field_name'], name='translation_content_15722a_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'field_name', 'language'), name='lang_field_name')],
            },
        ),
    ]
